name: Close PR, leave comment
on: 
  push
  
jobs:
  comment-and-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = context.commits[0].id;
            
            const commit = await github.rest.git.getCommit({
              commit_sha: sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log(`sha: ${sha}`);
            console.log(`full commit: ${commit}`);
