name: Close PR, leave comment
on: 
  push
  
jobs:
  comment-and-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if(context.payload.commits && context.payload.commits.length){
              const sha = context.payload.commits[0].id;

              const commit = (await github.rest.git.getCommit({
                commit_sha: sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })).data;
              
              console.log(sha)
              
              const getClosedPrIfExists= (commit) => {
              console.log(commit);
                if(!commit || !commit.message) return;
              
                const prClosingRegex = /Closes https:\/\/github.com\/facebook\/react-native\/pull\/([0-9]+)|Pull Request resolved: https:\/\/github.com\/facebook\/react-native\/pull\/([0-9]+)/;
                
                const prClosingMatch = commit.message.match(prClosingRegex);
                
                console.log(prClosingMatch);
                if(!prClosingMatch || !prClosingMatch[0]) return;
                return prClosingMatch[0];
              };
              
              const closedPrNumber = getClosedPrIfExists(commit);
              
              console.log(closedPrNumber);
              
              if(closedPrNumber){
                const commitAuthor = commit.author.name;
                console.log(commitAuthor);
                console.log(commit.author.login);
                
                //need to check if the PR has already been tagged
                
                const pr = await github.rest.pulls.get({
                  pull_number: closedPrNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })

                github.rest.issues.createComment({
                  issue_number: closedPrNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `This pull request was successfully merged by ${commitAuthor} in **${sha}**.\n\n<sup>[When will my fix make it into a release?](https://github.com/facebook/react-native/wiki/Release-FAQ#when-will-my-fix-make-it-into-a-release) | [Upcoming Releases](https://github.com/reactwg/react-native-releases/discussions/categories/releases)</sup>"
                `})

                github.rest.issues.addLabels({
                  issue_number: prNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["Merged"]
                })

              }
            }

